export enum HOUSE_WALLET_TYPES {
    GAS_STATION = 'GAS_STATION',
    TREASURY = 'TREASURY'
}

export enum COMPONENT_ORDER_STATUS {
    PENDING = 'PENDING',
    PROCESSING = 'PROCESSING',
    SUCCESS = 'SUCCESS',
    FAILED = 'FAILED'
}